using System;

using System.Collections.Generic;



namespace app.menu
{
    public enum ScreenId
    {
        START_LOADING, MAIN_MENU, STORY_CHOOSE_LEVEL, GAME_LOADING, INFO, HOW_TO_PLAY, ABOUT, BUY_FULL, RESUME_STORY, GAME_SCREEN, PAUSE_MENU, RESTART_LEVEL, STORY_START_MISSION, STORY_LEVEL_FAILED, LEVEL_UP, ENDLESS_FINISH, FRENZY_FINISH, HINT, ENDLESS_HINT, FRENZY_HINT, CHALLENGE_RESULT, LOADING, CHEATS, BOOSTS_SELECTOR
    }
    
    
}